# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ",dt"
    replace: "{{myDate}}"
    label: "Todays Date YYYY-MM-DD"
    vars:
      - name: "myDate"
        type: date
        params:
          format: "%Y-%m-%d"
  # - trigger: ",dt"
  #   label: "Todays Date MM-DD-YYYY"
  #   replace: "{{myDate}}"
  #   vars:
  #     - name: "myDate"
  #       type: date
  #       params:
  #         format: "%m/%d/%Y"
  - trigger: ",ts"
    label: "Created Timestamp"
    replace: "{{myTimestamp}}"
    vars:
      - name: "myTimestamp"
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S%:z"
  - trigger: "1/4"
    replace: "¼"
  - trigger: "1/2"
    replace: "½"
  - trigger: "3/4"
    replace: "¾"
  - trigger: "1/8"
    replace: "⅛"
  - trigger: "1/3"
    replace: "⅓"
  # And much more! For more information, visit the docs: https://espanso.org/docs/