' Color Descriptions found here: https://cdkglobal.frontify.com/document/8#/cdk-global-branding/brand-colors
' Primary Colors {{{
!$ColorPrimaryGreen = "#82C600"
!$ColorBlack = "#231F20"
!$ColorWhite = "#FFFFFF"
' }}}
' Secondary Colors {{{
!$ColorSecondaryGreen = "#509E2F"
!$ColorSecondaryTeal = "#00B2A9"
!$ColorSecondaryBlue = "#009CDE"
!$ColorSecondaryDarkTeal = "#00778B"
!$ColorSecondaryDarkBlue = "#005EB8"
!$ColorSecondaryBurgundy = "#890C58"
' }}}
' Neutral Colors {{{
!$ColorNeutralKhaki = "#E1D7B0"
!$ColorNeutralGray = "#A7A8AA"
' }}}
' Tertiary Colors {{{
!$ColorTertiaryOrange = "#ED0B00"
!$ColorTertiaryYellow = "#FEDB00"
' }}}

skinparam node {
  BackgroundColor <<Primary>> $ColorPrimaryGreen
  FontColor <<Primary>> $ColorWhite
}
